### ISSUE TITLE
Script issue!

### ISSUE THREAD

**Issue by anujdahiya24** [jbkunst/playing-chess#1]
I began running your script code, the parser.R script file,  and I am stumped by this error I came across. (Here is my console log)
#### Parameters

> PATH_RAWDATA  <- "data-raw"
> 
> PATH_SQL      <- "data-sqlite"
> DB_NAME       <- "db.sqlite"
> DB_PATH       <- file.path(PATH_SQL, DB_NAME) 
> 
> PATH_RDATA    <- "data-rdata"
> PATH_GZIP     <- "data-gzip"
> PATH_ALL      <- "data-all"
> 
> VERBOSE       <- TRUE
> #### Folders
> 
> l_ply(c(PATH_SQL, PATH_RDATA, PATH_GZIP, PATH_ALL), function(x){
> -   unlink(x, recursive = TRUE)
> -   file.remove(x)
> -   dir.create(x)
> - })

Warning messages:
1: In file.remove(x) :
  cannot remove file 'data-sqlite', reason 'No such file or directory'
2: In file.remove(x) :
  cannot remove file 'data-rdata', reason 'No such file or directory'
3: In file.remove(x) :
  cannot remove file 'data-gzip', reason 'No such file or directory'
4: In file.remove(x) :
  cannot remove file 'data-all', reason 'No such file or directory'

The files are there though, as displayed below.

![5253e0b0-a505-11e5-8dab-ca19a9](https://cloud.githubusercontent.com/assets/16270355/11888774/25391076-a507-11e5-98e3-6b1a92d24ef5.png)

Any thoughts why it is not actually locating the folders?

**Comment by jbkunst** [comment]
It's not a problem. Run again the code without remove manually the folders.
